name: site-testing
run-name: Runs unit test suite for the website
on:
  workflow_dispatch:
    inputs:
      silent:
        description: "Print log messsages in javascript files"
        type: boolean
        default: true
        
  pull_request:
    types: 
      - edited
    paths:
      - '*.jsx'
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'npm'
          
      - run: npm install
      - name: Run jest tests
        run: npm run test -- --silent=${{ toJSON(inputs.silent) }}
